### ISSUE TITLE
"Error: Unable to resolve enough promises" and "Bad private key"

### ISSUE THREAD

**Issue by gbalduzzi** [torusresearch/torus-embed#209]
**Describe the bug**
I'm trying to login to the testing environment (testing.tor.us) with my local app, but after completing the login flow I get an error in the console and login is stopped.

If I login with the very same provider directly on testing.tor.us, I can login without problems.

The console logs of the whole process:

Before the error:
```
version used:  1.5.4
app.js:6942 https://testing.tor.us url loaded
app.js:6942 setupWeb3 running
app.js:1 {type: "mainnet", rpcTarget: "mainnet", chainId: 1, ticker: "Main Ethereum Network", nickname: "Main Ethereum Network"}
app.js:1 NetworkController - configureInfuraProvider mainnet
app.js:1 VUE_APP_TORUS_BUILD_ENV testing
app.js:1 wallet initialised
app.js:6942 supported 3rd party cookies
app.js:1 STATIC DATA: {networkId: "loading"}
app.js:1 NetworkController - configureInfuraProvider mainnet
app.js:1 web3.getNetwork returned 1
app.js:1 STATIC DATA: {networkId: "1"}
app.js:1 RPC (local.geekytrivia.com): {method: "wallet_sendDomainMetadata", domainMetadata: {…}, id: 1188874417, origin: "local.geekytrivia.com"} -> {id: 1188874417, jsonrpc: undefined, result: true}
app.js:1 {currentEpoch: "18", nodeListAddress: "0x638646503746d5456209e33a2ff5e3226d698bea", torusNodeEndpoints: Array(9), torusNodePub: Array(9), torusIndexes: Array(9), …}
app.js:1 STATIC DATA: {networkId: "loading"}
app.js:1 NetworkController - configureInfuraProvider mainnet
app.js:1 web3.getNetwork returned 1
app.js:1 STATIC DATA: {networkId: "1"}
app.js:6942 {name: "provider_change_status", data: {…}}
app.js:1  accounts
app.js:1 RPC (local.geekytrivia.com): {method: "eth_requestAccounts", params: Array(0), jsonrpc: "2.0", id: 1188874418, origin: "local.geekytrivia.com"} -> {id: 1188874418, jsonrpc: "2.0", result: Array(0)}
app.js:1 p data: [{…}]
app.js:1 {instanceParams: {…}, hashParams: {…}, queryParams: {…}}
app.js:1 New private key assigned to user at address  0x9Ef94Df96415c9D0500EC09645754f985099E872
```

and then the error:
```
app.js:1 Error: Unable to resolve enough promises, errors: [null,null,null,null,null,null,null,null,null], responses: [
....
 predicate: Bad private key
```

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Both chrome and firefox

**Comment by tetratorus** [comment]
already fixed, please test again

**Comment by gbalduzzi** [comment]
In local I was not using https, I switched to https and everything worked

**Comment by kkamalyesh** [comment]
Hi, can you explain what you mean by switching to https?

**Comment by gbalduzzi** [comment]
> Hi, can you explain what you mean by switching to https?

Instead of http://local.site I configured and used https://local.site

**Comment by kkamalyesh** [comment]
so only change is, the app is running on https://local.site, and there are no other changes in code. Is this correct?
